version: "3"

services:
  app1:
    build:
      context: app
      dockerfile: Dockerfile
    hostname: app1
    volumes:
      - ./app/static:/static

  app2:
    build:
      context: app
      dockerfile: Dockerfile
    hostname: app2
    volumes:
      - ./app/static:/static

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "80:80"

volumes:
  files:
    driver: local
